import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import React from 'react';

export const metadata: Metadata = {
	title: 'Next',
	description: 'Generated by create next app',
};

const RootLayout = ({ children }: React.PropsWithChildren) => (
	<html lang="en" style={{ scrollBehavior: 'smooth', height: '100%' }}>
		<body>
			<AntdRegistry>{children}</AntdRegistry>
		</body>
	</html>
);

export default RootLayout;
